[package]
name = "ulferno/objecthighlighter"
description = "Port of rbx-ObjectHighlighter by Imaginaerume for use in Check it Containment"
version = "1.0.1"
license = "MIT"
authors = []
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"